### ISSUE TITLE
Update go.mod to include dependency versions

### ISSUE THREAD

**Issue by cosban** [parsyl/parquet#11]
This library does not support the use of the latest apache thrift library as they have broken their API by introducing new arguments into their exported functions. That event makes it impossible to install this library with `go get` because the older version is not defaulted to. By adding the specific required version (or by updating this library to be compatible while also still adding these versions to the go.mod) this library will become immediately usable again.

**Comment by cswank** [comment]
Thanks for pointing this out @cosban.  I just added thrift (0.13.0) and snappy to go.mod.
