### ISSUE TITLE
Concurrent usage

### ISSUE THREAD

**Issue by aminmir326** [parsyl/parquet#19]
Hi, I have a use-case where I'm writing billions of data entries into a file. I couldn't find any information regarding this in the README, so I wanted to ask whether it's safe to use `*ParquetWriter` across multiple goroutines to speed up the whole process and if you have any recommendations for doing that. I'm not quite sure but maybe `Add` could be called concurrently and every once in a while `Write` should be called depending on the size of RowGroup.

**Comment by cswank** [comment]
I haven't tried that, but I'm certain that concurrent writing would not be safe.  

One thing you might want to consider is writing your data to multiple parquet files instead.  At parsyl we build sensor devices and each device has its own parquet file, so we have 1000s of them.

You would just have to determine if there is a natural way to partition your data.  We parttion by device.  Maybe partitioning by date (one parquet file per month) or something like that might work for you too.

**Comment by aminmir326** [comment]
Thank you for the reply. I figured writing to multiple files would be the way to go.
